#index:
#    path: /
#    controller: App\Controller\DefaultController::index
# config/routes.yaml
controllers:
    resource: '../src/Action/'
    type: annotation

# redirecting the homepage to route which contains default locale
homepage:
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::urlRedirectAction
    defaults:
        path: /en
        permanent: true

disconnection:
    path:
        en: /{_locale}/logout
        fr: /{_locale}/deconnection